import requests
import logging
from functools import wraps
from typing import Optional
from .auth import Auth
from .queries import (
    GET_VEHICLE_REWARDS_QUERY,
    GET_LATEST_SIGNALS_QUERY,
    GET_ALL_VEHICLES_QUERY,
)

_LOGGER = logging.getLogger(__name__)


def requires_vehicle_jwt(method):
    """Decorator that fetches vehicle jwt and unpacks token into call"""

    @wraps(method)
    def wrapper(self, token_id: str, *args, **kwargs):
        vehicle_jwt = self._fetch_privileged_token(token_id)
        return method(self, vehicle_jwt, token_id, *args, **kwargs)

    return wrapper


class DimoClient:
    def __init__(self, auth: Auth):
        self.auth = auth
        self.dimo = auth.get_dimo()

    def init(self) -> None:
        """Initialize the client by retrieving an authorization token"""
        try:
            self.auth.get_access_token()
        except Exception as e:
            _LOGGER.error(f"Failed to init Dimo client: {e}")
            raise

    def _fetch_privileged_token(self, token_id: str) -> str:
        """Retrieve privileged token for specified token id"""
        try:
            # Assert access token validity
            self.auth.get_access_token()
            # Get privileged token with the granted permissions
            return self.auth.get_privileged_token(token_id).token
        except Exception as e:
            _LOGGER.error(f"Failed to obtain privileged token for {token_id}: {e}")
            raise

    def get_vehicle_makes(self):
        return self.dimo.device_definitions.list_device_makes()

    @requires_vehicle_jwt
    def lock_doors(self, vehicle_jwt: str, token_id: str):
        return self.dimo.devices.lock_doors(vehicle_jwt, token_id)

    @requires_vehicle_jwt
    def unlock_doors(self, vehicle_jwt: str, token_id: str):
        return self.dimo.devices.unlock_doors(vehicle_jwt, token_id)

    def get_rewards_for_vehicle(self, token_id: str):
        """Get total token rewards generated by vehicle"""
        query = GET_VEHICLE_REWARDS_QUERY.format(token_id=token_id)
        return self.dimo.identity.query(query)

    @requires_vehicle_jwt
    def get_available_signals(self, vehicle_jwt: str, token_id: str):
        """Get list of available signals for a specified vehicle"""
        return self.dimo.telemetry.available_signals(vehicle_jwt, token_id)

    @requires_vehicle_jwt
    def get_latest_signals(self, vehicle_jwt: str, token_id, signal_names: list[str]):
        """Get the latest signal values for the specified vehicle"""
        if signal_names is None:
            signal_names = []

        signals_query = "\n".join(
            [
                f"{signal_name} {{\n  timestamp\n  value\n}}"
                for signal_name in signal_names
            ]
        )

        query = GET_LATEST_SIGNALS_QUERY.format(
            token_id=token_id, signals=signals_query
        )
        return self.dimo.telemetry.query(query, vehicle_jwt)

    def get_all_vehicles_for_license(self, license_id=None):
        """List all vehicles for the specified license."""
        if license_id is None:
            license_id = self.auth.client_id

        query = GET_ALL_VEHICLES_QUERY.format(license_id=license_id)
        return self.dimo.identity.query(query)

    def get_total_dimo_vehicles(self) -> Optional[int]:
        """
        Get the total number of vehicles on DIMO.

        :return: Total count of vehicles or None if failed.
        """
        try:
            result = self.dimo.identity.count_dimo_vehicles()
            return result.get("data", {}).get("vehicles", {}).get("totalCount")
        except requests.exceptions.ConnectionError as ex:
            _LOGGER.warning(
                "DIMO API request error when retrieving DIMO vehicle count %s", ex
            )
            return None
        except Exception as e:
            _LOGGER.error(f"Failed to get total DIMO vehicles: {e}")
            return None

    @requires_vehicle_jwt
    def get_vin(self, vehicle_jwt: str, token_id) -> Optional[str]:
        """
        Retrieve the Vehicle Identification Number (VIN) for the specified token ID.

        :param token_id: Token ID associated with the vehicle.
        :return: The VIN as a string, or None if unavailable.
        """
        try:
            vin_response = self.dimo.telemetry.get_vin(vehicle_jwt, token_id)
            vin = vin_response.get("data", {}).get("vinVCLatest", {}).get("vin")
            if vin:
                _LOGGER.debug(
                    f"Successfully retrieved VIN for token_id {token_id}: {vin}"
                )
                return vin
            _LOGGER.warning(
                f"VIN not found in response for token_id {token_id}: {vin_response}"
            )
            return None
        except KeyError as e:
            _LOGGER.error(
                f"Malformed response when retrieving VIN for token_id {token_id}: {e}"
            )
            return None
        except requests.exceptions.ConnectionError as ex:
            _LOGGER.warning(
                "Connect error occurred while retrieving VIN for token id %s: %s",
                token_id,
                ex,
            )
            return None
        except Exception as e:
            _LOGGER.error(f"Failed to retrieve VIN for token_id {token_id}: {e}")
            return None
